theme: minima
plugins:
  - jekyll-feed

title: Блог Enigma0960
author:
  name: Igor Supryadkin
  email: igorsupr@google.com
description: Мой личный блог, где я делюсь своим опытом в разработке и реверс-инжиниринге.
